debug: true

server:
  port: 8020
  context-path: /dorsal

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dorsal
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  basic:
    enabled: false
  devtools:
    restart:
      enabled: false